name: social_media_app
description: "A social media app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  go_router: ^15.1.3
  nb_utils: ^7.1.4
  get_it: ^8.0.3
  path_provider: ^2.1.5
  crypto: ^3.0.6
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.4
  file_picker: ^10.2.0
  photo_manager: ^3.7.1
  video_player: ^2.10.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.4.6


flutter:
  uses-material-design: true

  assets:
    - assets/

# Splash screen:

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/app_icon.png
  android: true
  ios: true

  android_gravity: center
  ios_content_mode: center

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"